export const routes = {
  home: "/",
  pricing: "/pricing",
  integrations: "/integrations",
  login: "/login",
  /** Opens the Book a Demo modal on the current page (components/demo/bookDemoRequest.ts). */
  demo: "#book-demo",
  /** Opens the Start Free drawer on the current page (components/start-free/startFreeRequest.ts). */
  signup: "#start-free",

  platform: {
    all: "/platform",
    crm: "/crm-landing",
    /** Platform → Sales module page. (`/sales` is the Solutions → Sales page, see `solutions.sales`.) */
    sales: "/sales-module",
    /** Platform → Customer Service module page. (`/customer-service` is the Solutions → Customer Service page, see `solutions.customerService`.) */
    service: "/customer-service-module",
    hrms: "/hrms",
    finance: "/finance",
    projects: "/projects",
    procurement: "/procurement",
    inventory: "/inventory",
    /** Platform → Marketing module page. (`/marketing` is the Solutions → Marketing page, see `solutions.marketing`.) */
    marketing: "/marketing-module",
    analytics: "/analytics",
    automation: "/automation",
    ai: "/ai",
    aiInterview: "/ai-interview",
    aiAgents: "/ai-agents",
    aiAnalytics: "/ai-analytics",
    nlp: "/natural-language-processing",
    computerVision: "/computer-vision",
    speech: "/speech-to-text",
    aiRecommendations: "/ai-recommendations",
    intelligentAutomation: "/intelligent-automation",
    customModels: "/custom-ai-models",
    generativeAi: "/generative-ai",
    aiSearch: "/ai-search",
    cloudOnPremise: "/cloud-on-premise",
    multiCloud: "/multi-cloud-support",
    highAvailability: "/high-availability",
    scalableArchitecture: "/scalable-architecture",
    globalInfrastructure: "/global-infrastructure",
    backupRecovery: "/backup-disaster-recovery",
    performanceMonitoring: "/performance-monitoring",
    apiWebhooks: "/api-webhooks",
    mobileDesktopApps: "/mobile-desktop-apps",
    microservices: "/microservices-architecture",
    devops: "/devops-cicd",
    howItWorks: "/how-it-works",
    whiteLabel: "/white-label",
    tour: "/platform-tour",
    commerce: "/commerce",
  },

  solutions: {
    all: "/solutions",
    sales: "/sales",
    marketing: "/marketing",
    customerService: "/customer-service",
    ticketManagement: "/ticket-management",
    knowledgeBase: "/knowledge-base",
    slaManagement: "/sla-management",
    omnichannelSupport: "/omnichannel-support",
    customerInsights: "/customer-insights",
    salesAutomation: "/sales-automation",
    pipelineManagement: "/pipeline-management",
    quotesOrders: "/quotes-orders",
    salesAnalytics: "/sales-analytics",
    territoryManagement: "/territory-management",
    campaignManagement: "/campaign-management",
    leadGeneration: "/lead-generation",
    emailMarketing: "/email-marketing",
    customerJourney: "/customer-journey",
    marketingAnalytics: "/marketing-analytics",
    startups: "/solutions/startups",
    smallBusiness: "/solutions/small-business",
    enterprise: "/solutions/enterprise",
  },

  industries: {
    all: "/industries",
    technology: "/industries/technology",
    healthcare: "/industries/healthcare",
    education: "/industries/education",
    manufacturing: "/industries/manufacturing",
    retail: "/industries/retail",
    realEstate: "/industries/real-estate",
    financialServices: "/industries/financial-services",
    professionalServices: "/industries/professional-services",
    nonProfit: "/industries/non-profit",
    agencies: "/industries/agencies",
  },

  resources: {
    all: "/resources",
    blog: "/resources/blog",
    guides: "/resources/guides",
    webinars: "/resources/webinars",
    caseStudies: "/resources/case-studies",
    helpCenter: "/resources/help-center",
    apiDocumentation: "/resources/api-documentation",
  },

  company: {
    about: "/company/about",
    careers: "/company/careers",
    partners: "/company/partners",
    contact: "/company/contact",
    newsroom: "/company/newsroom",
  },

  legal: {
    privacy: "/legal/privacy-policy",
    terms: "/legal/terms-of-service",
    cookies: "/legal/cookie-policy",
  },
} as const;
